CREATE DATABASE SENSORDATA;
USE SENSORDATA;

CREATE TABLE Sensor_Data (
Timing VARCHAR(20),
Temperature DECIMAL(5,2),
Vib_X DECIMAL(8,3),
Vib_Y DECIMAL(8,3),
Vib_Z DECIMAL(8,3),
Magnitude DECIMAL(8,3),
RMS DECIMAL(8,3)
);

SELECT * FROM Sensor_Data;

# Primary Key - ID
ALTER TABLE Sensor_Data
ADD COLUMN ID INT AUTO_INCREMENT PRIMARY KEY;

ALTER TABLE Sensor_Data
MODIFY COLUMN ID INT NOT NULL AUTO_INCREMENT FIRST;

DESCRIBE Sensor_Data;